services:
  zmqtt2prom:
    container_name: zmqtt2prom
    image: yellowstonesoftware/zmqtt2prom:latest
    restart: unless-stopped
    environment:
      - Z2P_MQTT_HOST=mqtt.home.com
      - Z2P_MQTT_PORT=1883
      - Z2P_MQTT_USERNAME=
      - Z2P_MQTT_PASSWORD=
      - Z2P_LOG_LEVEL=info
      - Z2P_HTTP_PORT=8080
    ports:
      - "8080:8080"
